projectefinal/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'bibliotecaController@index')->name('biblioteca.index')->middleware('auth');

Route::get('biblioteca', 'bibliotecaController@index')->name('biblioteca.index')->middleware('auth');

Route::get('tenda', 'jocsController@index')->name('jocs.index')->middleware('auth');

Route::get('tenda/{joc}', 'jocsController@show')->name('jocs.show')->middleware('auth');

Route::get('perfil/{id}', 'profileController@show')->name('perfil.show')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('users/{user}',  ['as' => 'users.edit', 'uses' => 'profileController@edit'])->middleware('auth');

Route::patch('users/{user}/update',  ['as' => 'users.update', 'uses' => 'profileController@update']);

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->middleware('auth');

Route::post('comentaris/{id}', 'comentarisController@store')->name('comentaris.store')->middleware('auth');

Route::post('/search', 'searchController@show')->name('search.show')->middleware('auth');

Route::post('puntuacio/{id}', 'comentarisController@puntuar')->name('comentaris.puntuar')->middleware('auth');

projectefinal/app/Http/Controllers/jocsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\joc;
use App\User;
use App\biblioteca;
use Illuminate\Support\Facades\Auth;
use App\comentari;
use \Crypt;

class jocsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //RETORNAR TOTS ELS JOCS AMB LA VISTA DE LA TENDA
        $jocs = joc::withCount('comentari')->get();
        $ranking = $this->getRank();
        $numerocomentaris = 0;

        return view('shop',array('jocs'=>$jocs,'ranking'=>$ranking));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        

        //DONADA ID JOC, RETORNAR VISTA AMB EL JOC PER COMPRAR
        $id = Crypt::decrypt($id);
        $usuarilogin = Auth::user();
        $biblio = biblioteca::where('id_usuari', $usuarilogin->id)->where('id_joc', $id)->first();
        $joc = joc::where('id', $id)->firstOrFail();
        //GET TOTS ELS COMENTARIS + USUARI DONADA ID DE JOC 
        $comentaris = comentari::where('joc_id', $id)->with('user')->get();
        //obtenim la biblioteca de l'usuari per a saber quins jocs te
        $biblioteca = biblioteca::where('id_usuari',$usuarilogin->id)->get();
        $tejoc = null;
        foreach($biblioteca as $jocbib){
            if($jocbib->id_joc == $joc->id){
                $tejoc = $jocbib;
            }
        }
        return view('product',['joc'=> $joc,'comentaris'=>$comentaris,'tejoc'=>$tejoc, 'biblio'=>$biblio]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getRank()
    {
        $taula = joc::orderBy('puntuacio', 'DESC')->get();

        return $taula;
    }
}

projectefinal/resources/views/biblioteca.blade.php
@extends("layouts.plantilla")
@push('styles')
<link href="{{ asset('css/biblioteca.css') }}" rel="stylesheet">
@endpush
@section("contingut")

<!-- a -->
<div class="wrapper" id="app">
@if ($message = Session::get('success'))
  <!-- al registrar.. mirar RegistersUsers.php -->
  <!-- The Modal -->
  <div id="registre" class="modal">
    
    <!-- Modal content -->
    <div class="modal-content d-flex justify-content-between">
      <span class="close">&times;</span>
      <p id="textBenvinguda">Benvingut a AM Platform, la plataforma líder en els jocs Arcade <i class="fa fa-gamepad"></i>
        <br>Per començar, et regalem 10 monedes <i class="fa fa-money"></i> perquè puguis comprar els jocs que més t'agraden!

        <br>Abans de començar a jugar, et guiarem amb el menú...
      </p>
      <button type="submit" id="botonext" class="btn btn-dark" v-on:click="next()">Seguent</button>
    </div>
  </div>
  @endif
  <div id="frame" class="container frames">

  </div>
  <div class="container" id="biblioteca">
    <h1>Biblioteca</h1>
    <br>
    <div class="row">

      @forelse($biblioteca as $joc)
      <div class="col-md-4">
        <div class="card" id="fila" style="width: ;">
          <a href="{{route('jocs.show',Crypt::encrypt($joc->id))}}"><img class="card-img-top" src="{{$joc->img}}"></a>
          <div class="card-body">
            <a href="{{route('jocs.show',Crypt::encrypt($joc->id))}}">
              <h5 class="card-title text-light">{{$joc->nom}}</h5>
            </a>
            <p class="card-text text-light">{{str_limit($joc->descripcio,100)}}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item gris">Temps jugat: <span id="{{$joc->id}}">{{$joc->tempsjugat}}</span> segons</li>
            <li class="list-group-item gris">La meva puntuació:
              @switch($joc->puntuacio)
              @case(0)
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              @break
              @case(1)
              <i class="fa fa-star"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              @break
              @case(2)
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              @break
              @case(3)
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-o"></i>
              <i class="fa fa-star-o"></i>
              @break
              @case(4)
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-o"></i>
              @break
              @case(5)
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              @break
              @endswitch
            </li>
            <li class="list-group-item text-dark gris">
              @foreach($bibliotecaamics as $bib)
              @foreach($bib as $bib)
              @if($bib->id_joc == $joc->id)
              <a class="amicslink" href="{{route('perfil.show',Crypt::encrypt(App\Http\Controllers\userController::show($bib->id_usuari)->id))}}">
                <div id="fotousuaris" style="background-image: url({{App\Http\Controllers\userController::show($bib->id_usuari)->fotoperfil}})">&nbsp</div>
              </a>
              <p class="amics">{{App\Http\Controllers\userController::show($bib->id_usuari)->nickname}}</p>
              @endif
              @endforeach
              @endforeach
            </li>
          </ul>
          <div class="card-body">
            <button class="btn btn-dark" v-on:click="obrirjoc({{$joc->id}},'{{$joc->identificador}}',{{session()->get('usuarilogin')->id}})">Jugar</button>
          </div>
        </div>
      </div>
      @empty
      <div class="container">
        <div class="jumbotron" style="color:black">
          <h1>No tens cap joc!</h1>
          <p>No pateixis, pots comprar el primer <a id="tenda" href="{{route('jocs.index')}}">aqui!</p>
        </div>
      </div>
      @endforelse
    </div>
  </div>
</div>

@endsection

projectefinal/resources/views/editprofile.blade.php
@extends("layouts.plantilla")

@push('styles')
    <link href="{{ asset('css/perfiledit.css') }}" rel="stylesheet">
@endpush

@section("contingut")

@if(count($errors)>0)

    <ul>
        @foreach($errors->all() as $error)

            <div class="alert alert-danger col-sm-11">{{$error}}</div>

        @endforeach
    </ul>

@endif

<form method="post" action="{{route('users.update', $user->id)}}">

    {{ csrf_field() }}
    {{ method_field('patch') }}

<div class="container" style="color: white">

    <div class="form-group">
        <label class="col-sm-2 control-label">Nom</label>
        <div class="col-sm-11">
            <input type="text" name="name" class="form-control" value="{{ $user->nom }}">
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-2 control-label">Cognom</label>
        <div class="col-sm-11">
            <input type="text" name="surname" class="form-control" value="{{ $user->cognom }}">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="nickname">Nickname</label>
        <div class="input-group col-sm-11">
            <div class="input-group-prepend">
                <div class="input-group-text">@</div>
            </div>
            <input type="text" name="nickname" class="form-control" id="nickname" placeholder="Nickname" value="{{ $user->nickname }}">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">URL avatar</label>
        <div class="col-sm-11">
            <input type="text" name="avatar" class="form-control" placeholder="http://exemple.com/foto.png" value="{{ $user->fotoperfil }}">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">URL fons perfil</label>
        <div class="col-sm-11">
            <input type="text" name="background" class="form-control" placeholder="http://exemple.com/foto.png" value="{{ $user->background }}">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Contrasenya atual</label>
        <div class="col-sm-11">
            <input type="password" name="oldpassword" class="form-control">
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-2 control-label">Nova contrasenya</label>
        <div class="col-sm-11">
            <input type="password" name="newpassword" class="form-control" name="password" id="password2" onkeyup="checkPass();">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Confirmar contrasenya</label>
        <div class="col-sm-11">
            <input type="password" name="confirmpassword" class="form-control" name="confirm" id="confirm2" onkeyup="checkPass();">
            <span id="confirm-message2" class="confirm-message"></span>
        </div>
    </div>
    
    
    <div class="form-group">
        <div class="col-sm-11 col-sm-offset-2">
            <button type="submit" class="btn btn-primary" id="botosubmit">Submit</button>
            <button type="reset" class="btn btn-default">Cancel</button>
        </div>
    </div>

</div>

</form>

<script>
    
function checkPass()
{
    var password = document.getElementById('password2');
    var confirm  = document.getElementById('confirm2');

    var message = document.getElementById('confirm-message2');

    //Set the colors we will be using ...
    var good_color = "#70E46E";
    var bad_color  = "#E4836E";

    //Compare the values in the password field 
    //and the confirmation field
    if(password.value == confirm.value){
        //The passwords match. 
        //Set the color to the good color and inform
        //the user that they have entered the correct password 
        confirm.style.backgroundColor = good_color;
        message.style.color           = good_color;
    }else{
        //The passwords do not match.
        //Set the color to the bad color and
        //notify the user.
        confirm.style.backgroundColor = bad_color;
        message.style.color           = bad_color;
    }
}  
</script>
@endsection

projectefinal/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

projectefinal/resources/views/product.blade.php
@extends("layouts.plantilla")

<head>
  <title>{{$joc->nom}}</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

  <link href="{{ asset('css/product.css') }}" rel="stylesheet">

</head>

@section("contingut")
@if(count($errors)>0)

<ul>
  @foreach($errors->all() as $error)

  <div class="alert alert-danger col-sm-11">{{$error}}</div>

  @endforeach
</ul>

@endif
<div id="snackbar">Disfruta del joc <a class="btn btn-primary" href="{{route('biblioteca.index')}}">Jugar</a></div>
<div class="container" id="app">
  <div class="card" style="background-color: #1A1A1A; border-bottom: 1px solid #d19b3d; border-left: 1px solid #d19b3d; color:white;">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview ">
          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1"><img class="fotojoc" src="{{$joc->img}}" /></div>
          </div>

        </div>
        <div class="col-md-6">
          <h3 class="product-title">{{$joc->nom}}</h3>
          <h4 class="price">Descripció: </h4>
          <!-- <p class="product-description">{{$joc->descripcio}}</p> -->
          <p class="product-description">{{$joc->descripcio}}</p>
          <div class="form-inline">
            <div class="form-group">
              <h4>Puntuació: @switch($joc->puntuacio)
                @case(0)
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(1)
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(2)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(3)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(4)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(5)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                @break
                @endswitch
              </h4>
            </div>
          </div>
          <h4 class="price">PREU: <span>{{$joc->preu}}€</span></h4>
          <div id="posicioboto" class="action">
            @if($tejoc == null)
            <a id="{{$joc->id}}" class="add-to-cart btn btn-default" v-on:click="comprarJoc({{session()->get('usuarilogin')->id}},{{$joc->id}},{{$joc->preu}})">Comprar</a>
            @else
            <a id="{{$joc->id}}" class="add-to-cart btn btn-default" href="{{route('biblioteca.index')}}">Jugar</a>
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
  
  @if($biblio!=null)
  <div class="card" style="background-color: #1A1A1A; border-bottom: 1px solid #d19b3d; border-left: 1px solid #d19b3d; color:white;">
  <h3>Puntua:</h3>
    @if($biblio!=null)
    @if($biblio->puntuacio != 0 || $biblio->puntuacio != null)
    
    <div class="form-inline">
      <div class="form-group">
        <h5>La teva puntuacio actual: {{$biblio->puntuacio}}/5</h5>
      </div>
    </div>
    @endif
    @endif
    
    <form class="inline-form" method="post" action="{{route('comentaris.puntuar', $joc->id)}}">
      @csrf
      <label for="sel1">Nota:</label>

      <select class="form-control col-md-4" name="puntuacio">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option selected="selected">5</option>
      </select>
      <br>
      <input type="hidden" name="joc_id" value="{{$joc->id}}">

      @if($biblio->puntuacio != 0 || $biblio->puntuacio != null)
      <input class="btn btn-dark" type="submit" value="Actualitzar la puntuacio">
      @else
      <input class="btn btn-dark" type="submit" value="Puntuar aquest joc">
      @endif

    </form>
  </div>
    @endif
  
  <div class="card" style="background-color: #1A1A1A; border-bottom: 1px solid #d19b3d; border-left: 1px solid #d19b3d; color:white;">
    <h3>Comenta:</h3>
    <form method="post" action="{{route('comentaris.store', $joc->id)}}">
      @csrf
      <textarea name="comentari" class="form-control" style="background-color: #2e353d; color: white;"></textarea>
      <input type="hidden" name="joc_id" value="{{$joc->id}}">

      <br><input class="btn btn-dark" type="submit" value="Publica">
    </form>
    <div class="card-body">
      @forelse ($comentaris->reverse() as $comentari)
      <a class="dades" href="{{route('perfil.show',Crypt::encrypt($comentari->user->id))}}">
        <div id="fotousuaris" style="background-image: url({{$comentari->user->fotoperfil}})">&nbsp</div>
      </a><a class="dades" href="{{route('perfil.show',Crypt::encrypt($comentari->user->id))}}">{{$comentari->user->nickname}}</a>
      <p class="data">{{$comentari->created_at}}</p>
      <p>{{ $comentari->comentari }}</p>
      <hr>
      @empty
      <p>Encara no hi ha comentaris per aquest joc</p>
      @endforelse
    </div>
  </div>
  @endsection

projectefinal/resources/views/profile.blade.php
@extends("layouts.plantilla")
@push('styles')
<link href="{{ asset('css/perfil.css') }}" rel="stylesheet">
<style>
  #image1 {
    background-image: url({{$user->fotoperfil}});
  }

  #banner {
    background-image:url({{$user->background}});
  }
</style>
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
@endpush


<body class="profile-page sidebar-collapse">
  @section("contingut")

  <div class="wrapper">
    <!-- The Modal -->
    <div id="popup" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <span class="tancar">&times;</span>
        <div class="row">
          <div class="col" style="color: #d19b3d">Jocs
            <div class="list-group text-dark">
              @forelse($jocs as $joc)
              @foreach($joc as $joc)
              <a class="list-group-item list-group-item-action linknegre" style="display:inline-block" href="{{route('jocs.show',Crypt::encrypt($joc->id))}}">
                <div id="fotojocs" style="background-image: url({{$joc->img}})">&nbsp</div>
                {{$joc->nom}}
              </a>
              @endforeach
              @empty
              <p style="color: white;">Aquest usuari enara no té cap joc </p>
              @endforelse


            </div>
          </div>

          <div class="col" style="color: #d19b3d;">Amics
            <div class="list-group text-dark">
              @forelse($amics as $amic)
              @if($amic->user1_id!=$user->id)
              <a class="list-group-item list-group-item-action linknegre" style="display:inline-block" href="{{route('perfil.show',Crypt::encrypt(App\Http\Controllers\userController::show($amic->user1_id)->id))}}">
                <div id="fotousuaris" style="background-image: url({{App\Http\Controllers\userController::show($amic->user1_id)->fotoperfil}})">&nbsp</div>
                {{App\Http\Controllers\userController::show($amic->user1_id)->nickname}}
              </a>
              @elseif($amic->user2_id!=$user->id)
              <a class="list-group-item list-group-item-action linknegre" style="display:inline-block" href="{{route('perfil.show',Crypt::encrypt(App\Http\Controllers\userController::show($amic->user2_id)->id))}}">
                <div id="fotousuaris" style="background-image: url({{App\Http\Controllers\userController::show($amic->user2_id)->fotoperfil}})">&nbsp</div>
                {{App\Http\Controllers\userController::show($amic->user2_id)->nickname}}
              </a>
              @endif
              @empty
              <p style="color:white">Aquest usuari no té amics</p>
              @endforelse
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="page-header">
      <div id="overlay" class="page-header-image">
      </div>
      <div id="banner" class="page-header-image" data-parallax="true">
      </div>
      <div class="container">
        <div id="image1" class="cropcircle photo-container"></div>
        <h3 class="title">{{$user->nickname}}</h3>
        <p class="category">{{$user->nom}} {{$user->cognom}}</p>
        <div class="content">
          <a href="#" id="botopopup">
            <div class="social-description">
              <h2>{{count($biblioteca)}}</h2>
              <p class="text-light">Jocs</p>
            </div>
            <div class="social-description">
              <h2>{{count($amics)}}</h2>
              <p class="text-light">Amics</p>
            </div>
          </a>
        </div>
      </div>
    </div>
    <div id="botozindex" class="section">
      <div class="container" id="app">
        @if($user->id != session()->get('usuarilogin')->id)
        <div class="button-container">
          @if($friendship != null)
          @if($friendship->actiu == 0)
          @if($friendship->user1_id == session()->get('usuarilogin')->id)
          <a id="boto" href="#button" class="btn btn-primary btn-round btn-lg disabled" disabled>Solicitud enviada</a>
          @else
          <a id="botoprofile" href="#button" class="btn btn-primary btn-round btn-lg" v-on:click="acceptarsolicitud({{$user->id}},{{session()->get('usuarilogin')->id}})">Acceptar</a>
          <a id="botoprofile" href="#button" class="btn btn-primary btn-round btn-lg" v-on:click="declinarsolicitud({{$user->id}},{{session()->get('usuarilogin')->id}})">Declinar</a>
          @endif
          @elseif($friendship->actiu == 1)
          <a id="boto" href="#button" class="btn btn-primary btn-round btn-lg" v-on:click="declinarsolicitud({{$user->id}},{{session()->get('usuarilogin')->id}})">Deixar de ser amics</a>
          @endif
          @elseif($friendship == null)
          <a id="boto" href="#button" class="btn btn-primary btn-round btn-lg" v-on:click="enviarsolicitud({{$user->id}},{{session()->get('usuarilogin')->id}})">Enviar solucitud d'amistat</a>
        </div>
        @endif
        @endif
        @endsection
</body>

projectefinal/resources/views/shop.blade.php
@extends("layouts.plantilla")
@push('styles')
    <link href="{{ asset('css/tenda.css') }}" rel="stylesheet">
@endpush

@section("contingut")
<div class="container">
<h1>Botiga</h1>
<hr>

<div class="row no-gutters">


@foreach($jocs as $joc)


<div class="col-12 col-sm-6 col-md-8 position-relative" >
	<figure class="card card-product" id="fila">
		<div class="img-wrap"><a href="{{route('jocs.show',Crypt::encrypt($joc->id))}}"><img src="{{ asset($joc->img) }}"></a></div>
		<figcaption class="info-wrap" style="border-top:none">
				<a class="title text-light" href="{{route('jocs.show',Crypt::encrypt($joc->id))}}">{{$joc->nom}}</a>
				<p class="desc">{{str_limit($joc->descripcio,100)}}</p>
				<div class="rating-wrap">
					<div class="label-rating text-light"><p>Comentaris: {{$joc->comentari_count}} |</p></div>
					<div class="label-rating text-light"><p>Puntuacio: 
					@switch($joc->puntuacio)
                @case(0)
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(1)
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(2)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(3)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(4)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
                @break
                @case(5)
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                @break
              @endswitch
					</p></div>
				</div> <!-- rating-wrap.// -->
		</figcaption>
		<div class="bottom-wrap" style="border-top:1px solid #d19b3d;">	
			<div class="price-wrap h5">
				<span class="price-new">{{ $joc->preu }}€</span>
			</div> <!-- price-wrap.// -->
		</div> <!-- bottom-wrap.// -->
	</figure>
</div> <!-- col // -->


@endforeach

<div class="col-md-3 text-light position-fixed" id="jdr" style="right:0.5%">

<div class="list-group" id="ranquing">
	<div class="card-header ranking">RANKING JOCS</div>
@foreach($ranking as $rank)
  	<a href="{{route('jocs.show',Crypt::encrypt($rank->id))}}" class="ranking2 list-group-item list-group-item-action">
    <div class="row d-flex justify-content-between">
      <div class="row col-md-8 d-flex justify-content-start">
      <p>{{$loop->iteration}}&emsp;</p>
      <img src="{{$rank->img}}" width="30px" height="30px">
      &emsp;
      <p>{{$rank->nom}}</p>
      
      </div>

      <div class="row col-md-4 d-flex justify-content-end">
      <p>{{$rank->puntuacio}} <i class="fa fa-star"></i>
      @if($loop->iteration == 1)
      <i class="fa fa-trophy"></i>
      @elseif($loop->iteration == 2)
      <i class="fa fa-bookmark"></i>
      @elseif($loop->iteration == 3)
      <i class="fa fa-bookmark-o"></i>
      </p>
      @endif
      </div>
    </div>
		
	</a>
@endforeach

</div>
</div>  

</div> <!-- row.// -->


</div> 

@endsection